import torch
import torch.nn.functional as F

# Attention

https://easyai.tech/ai-definition/attention/

In [1]:
!which python

/Users/quantux/opt/mamba/bin/python


In [8]:
import torch
import torch.nn.functional as F

In [3]:
import sys
print(sys.executable)

/Users/quantux/opt/mamba/bin/python


In [30]:
x1 = torch.tensor([[1, 2, 1],[-1, -1,-2.0]])
x2 = torch.tensor([[2, 2, 1],[-1,-2, -1.0]])

x1

tensor([[ 1.,  2.,  1.],
        [-1., -1., -2.]])

In [31]:
x2

tensor([[ 2.,  2.,  1.],
        [-1., -2., -1.]])

In [32]:
raw_weights = torch.matmul(x1, x2.transpose(0,1))
raw_weights

tensor([[ 7., -6.],
        [-6.,  5.]])

In [34]:
attn_weights = F.softmax(raw_weights, dim=0)
attn_weights

tensor([[1.0000e+00, 1.6701e-05],
        [2.2603e-06, 9.9998e-01]])

In [35]:
attn_outputs = torch.matmul(attn_weights, x2)
attn_outputs

tensor([[ 2.0000,  2.0000,  1.0000],
        [-1.0000, -2.0000, -1.0000]])